### ISSUE TITLE
Automated matrix representation of QCQP for constructing SDP relaxation process less tedious

### ISSUE THREAD

**Issue by blegat** [Shuvomoy/BnB-PEP-code#1]
As a follow up to our discussion. Here is how to get the matrix representation of a QCQP.
The hope is to have at some point an easy to use and well documented solution in MOI or https://github.com/jump-dev/MatrixOptInterface.jl but it's not the case at the moment.
So given a constraint reference `con_ref`, do
```julia
using JuMP
JuMP.@variable(model, x)
JuMP.@variable(model, y)
index_map = MOI.Utilities.IndexMap()
index_map[JuMP.index(x)] = MOI.VariableIndex(1)
index_map[JuMP.index(y)] = MOI.VariableIndex(2)
n = 2

# ...
obj = JuMP.constraint_object(con_ref)
func = JuMP.moi_function(obj)
using DiffOpt
matrix = DiffOpt.sparse_array_representation(func, n, index_map)
matrix.quadratic_terms # gives you the Q matrix of `x'Qx/2` (beware the division by 2)
matrix.affine_terms # gives you the a vector of `a'x`
```
The `index_map` gives the mapping from the JuMP variables to the rows/columns so the output of the map should be 1 to `n` where `n` is the number of variables.

Let me know if it works.

**Comment by Shuvomoy** [comment]
Thanks @blegat ! I will try your suggestion on the simpler [QCQP](https://shuvomoy.github.io/blogs/posts/Solving_bilinear_optimization_problem_using_JuMP/) I showed you today, and I will let you know if it works.

**Comment by Shuvomoy** [comment]
Hi @blegat , 

I was trying to run your suggestion regarding extracting the matrices from a QCQP on a simple test example. However, I am running into an error while extracting the matrices.  I will describe the test QCQP, and then the code that giving error.

First, I have a simple QCQP that solves without any problem (code below).

```
using JuMP, Gurobi, DiffOpt
## Direct model
nonlinear_model = Model(Gurobi.Optimizer)
set_optimizer_attribute(nonlinear_model, "NonConvex", 2)
@variable(nonlinear_model, x)
@variable(nonlinear_model, y)
@constraint(nonlinear_model, con1, x^2 + y^2 - 4 == 0)
@constraint(nonlinear_model, con2, (x-1)^2 + y^2 - 4 == 0)
@objective(nonlinear_model, Min, x)
optimize!(nonlinear_model)
p_star = objective_value(nonlinear_model)
x_star = value.(x)
@show p_star
@show x_star
```
 
which has solution `p_star = 0.5, x_star = [0.5, -1.9364916731037083]`, correctly computed by `Gurobi+JuMP`.

However, trying to find the matrix using your suggestion runs into an error. Code is as follows. 

```
object_1 = JuMP.constraint_object(con1) # runs fine
quad_func_1 = JuMP.moi_function(object_1) # runs fine
matrix_1 = DiffOpt.sparse_array_representation(quad_func_1) # throws error
```
The error is: 

```
ERROR: MethodError: no method matching sparse_array_representation(::MathOptInterface.ScalarQuadraticFunction{Float64})
Closest candidates are:
  sparse_array_representation(::MathOptInterface.ScalarQuadraticFunction, ::Any, ::Any) at C:\Users\shuvo\.julia\packages\DiffOpt\B6lhV\src\utils.jl:50
  sparse_array_representation(::MathOptInterface.AbstractFunction, ::Any) at C:\Users\shuvo\.julia\packages\DiffOpt\B6lhV\src\utils.jl:62      
  sparse_array_representation(::Array{MathOptInterface.ScalarAffineTerm{T}, 1}, ::Any, ::Any) where T at C:\Users\shuvo\.julia\packages\DiffOpt\B6lhV\src\utils.jl:4
```

Let me know if you have any tips/suggestions.

**Comment by blegat** [comment]
Indeed, I have corrected my message above. Let me know if it works now

**Comment by Shuvomoy** [comment]
Sounds good @blegat , I will try it and will let you know!

**Comment by Shuvomoy** [comment]
Hi @blegat , it appears that I am getting the constant terms of the quadratic constraints incorrect if you follow the suggested code snippet. For example, for the problem: 

```
using JuMP, Gurobi, MosekTools, Mosek, LinearAlgebra, DiffOpt
## Direct model
nonlinear_model = Model(Gurobi.Optimizer)
set_optimizer_attribute(nonlinear_model, "NonConvex", 2)
@variable(nonlinear_model, x)
@variable(nonlinear_model, y)
index_map = MOI.Utilities.IndexMap()
index_map[JuMP.index(x)] = MOI.VariableIndex(1)
index_map[JuMP.index(y)] = MOI.VariableIndex(2)
n = 2
@constraint(nonlinear_model, con1, x^2 + y^2 - 4 == 0)
@constraint(nonlinear_model, con2, (x-1)^2 + y^2 - 4 == 0)
@objective(nonlinear_model, Min, x)
optimize!(nonlinear_model)
p_star = objective_value(nonlinear_model)
x_star = value.(x)
@show p_star
@show x_star
```

the constraint `con2` has the standard form `x^T P_2 x + q_2^T x + r_2`, where `P_2 = I`, `q_2=[-2;0]` and `r_2 = -3`. However the code below is providing me `r_2=0`, which is not correct (`P_2` and `q_2` are correct). 

```
object_1 = JuMP.constraint_object(con1)
quad_func_1 = JuMP.moi_function(object_1)
matrix_1 = DiffOpt.sparse_array_representation(quad_func_1, n, index_map)
P_1, q_1, r_1 = 0.5*matrix_1.quadratic_terms, matrix_1.affine_terms, matrix_1.constant


object_2 = JuMP.constraint_object(con2)
quad_func_2 = JuMP.moi_function(object_2)
matrix_2 = DiffOpt.sparse_array_representation(quad_func_2, n, index_map)
P_2, q_2, r_2 = 0.5*matrix_2.quadratic_terms, matrix_2.affine_terms, matrix_2.constant
```

The output shows that `r_2 = 0`.  Let me know your thoughts/suggestions.

**Comment by blegat** [comment]
The constant will always be zero as it is in the set. You can get it with
```julia
MOI.constant(JuMP.moi_set(obj))
```

**Comment by Shuvomoy** [comment]
Thanks @blegat , `MOI.constant(JuMP.moi_set(.))`  indeed gives the constant (though the sign should be negative).

```
MOI.constant(JuMP.moi_set(object_1)) # outputs 4 
MOI.constant(JuMP.moi_set(object_2)) # outputs 3
```
